--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-30 11:49:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 24577)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24583)
-- Name: produtos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos (
    id integer NOT NULL,
    nome character varying(50) NOT NULL,
    descricao character varying(100) NOT NULL,
    preco numeric NOT NULL,
    imagemurl text,
    categoria character varying(50)
);


ALTER TABLE public.produtos OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 24582)
-- Name: produtos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24591)
-- Name: produtos_mais_pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos_mais_pedidos (
    id integer NOT NULL,
    produto_id integer NOT NULL,
    categoria text
);


ALTER TABLE public.produtos_mais_pedidos OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24590)
-- Name: produtos_mais_pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtos_mais_pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_mais_pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4752 (class 2606 OID 24581)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4754 (class 2606 OID 24589)
-- Name: produtos PK_produtos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT "PK_produtos" PRIMARY KEY (id);


--
-- TOC entry 4757 (class 2606 OID 24595)
-- Name: produtos_mais_pedidos PK_produtos_mais_pedidos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos_mais_pedidos
    ADD CONSTRAINT "PK_produtos_mais_pedidos" PRIMARY KEY (id);


--
-- TOC entry 4755 (class 1259 OID 24601)
-- Name: IX_produtos_mais_pedidos_produto_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_produtos_mais_pedidos_produto_id" ON public.produtos_mais_pedidos USING btree (produto_id);


--
-- TOC entry 4758 (class 2606 OID 24616)
-- Name: produtos_mais_pedidos FK_produtos_mais_pedidos_produtos_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos_mais_pedidos
    ADD CONSTRAINT "FK_produtos_mais_pedidos_produtos_produto_id" FOREIGN KEY (produto_id) REFERENCES public.produtos(id) ON DELETE CASCADE;


-- Completed on 2025-06-30 11:49:58

--
-- PostgreSQL database dump complete
--

